### ISSUE TITLE
Support for GTK 3.22

### ISSUE THREAD

**Issue by phil-harmoniq** [nullbio/arc-new-darker#1]
Hello, I'm trying to use your theme in Ubuntu 17.04 and it won't load properly. I'm assuming it's because the original Arc theme needs to be recompiled for GTK 3.22, but I'm unable to figure out what you changed to compile it properly. Any chance you could provide an update compatible with newer GTK?

**Comment by nullbio** [comment]
I'm not really in a position to test this sorry (don't have a compatible system and am very busy atm), your optimal path forward would probably be to use the original repo and then manually merge the CSS changes from this repo into that.
